// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr_DVmuoSbpcEHHQYbuDCbtImpKueXWes',
    appId: '1:896286332308:web:0f94be8c2f10ecf1c52b81',
    messagingSenderId: '896286332308',
    projectId: 'event-checkin-51cae',
    authDomain: 'event-checkin-51cae.firebaseapp.com',
    storageBucket: 'event-checkin-51cae.firebasestorage.app',
    measurementId: 'G-WR7QM1V0DY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkqKqLQ3zuL6rttpX-iHaoxByHNaeERwA',
    appId: '1:896286332308:android:a3cb5dee1f88cc38c52b81',
    messagingSenderId: '896286332308',
    projectId: 'event-checkin-51cae',
    storageBucket: 'event-checkin-51cae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFQVzBiq9bKuCYOeXj93-iRpRVBeP9gkU',
    appId: '1:896286332308:ios:5faa54d21675ebc4c52b81',
    messagingSenderId: '896286332308',
    projectId: 'event-checkin-51cae',
    storageBucket: 'event-checkin-51cae.firebasestorage.app',
    iosBundleId: 'com.example.eventCheckin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFQVzBiq9bKuCYOeXj93-iRpRVBeP9gkU',
    appId: '1:896286332308:ios:5faa54d21675ebc4c52b81',
    messagingSenderId: '896286332308',
    projectId: 'event-checkin-51cae',
    storageBucket: 'event-checkin-51cae.firebasestorage.app',
    iosBundleId: 'com.example.eventCheckin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr_DVmuoSbpcEHHQYbuDCbtImpKueXWes',
    appId: '1:896286332308:web:9384b0c33bdf0024c52b81',
    messagingSenderId: '896286332308',
    projectId: 'event-checkin-51cae',
    authDomain: 'event-checkin-51cae.firebaseapp.com',
    storageBucket: 'event-checkin-51cae.firebasestorage.app',
    measurementId: 'G-CVK37R5GPQ',
  );
}
